config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'hotelapps#top'
  get 'hotelapps/top', to: 'hotelapps#top', as: 'top_hotelapp'
  get 'users/show', to: 'users#show', as: 'show_user'
  #get 'rents/new/:id', to: 'rents#new', as: :rents_new #アクションでホテルのidを取得
  resources :users, only: [:show] 
  resources :hotelapps do
    resources :rents, only: [:new]
    collection do
      get 'search'
    end
  end
  resources :rents do
    #post :confirm, action: :confirm, on: :new
  end
  resources :users
  #resources :hotelapps だとhotelapps/topへのルーティングができなかった。なぜ？
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :hotelapp

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :number, presence: true, numericality: { greater_than_or_equal_to: 1, less_than: 20 }

  validate :date_cannot_be_in_the_past 
  def date_cannot_be_in_the_past
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "：過去の日付は無効です") 
    end

    if end_date.present? && end_date < Date.today
      errors.add(:end_date, "：過去の日付は無効です") 
    end

    if end_date.present? && end_date < start_date
      errors.add(:end_date, "：終了日は開始日より前に指定はできません")
    end
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController

  before_action :authenticate_user!

  def index
    @rents = current_user.rents
  end

  def show #ルーム詳細
    @rent = Rent.find(params[:id])
    @hotelapp = Hotelapp.find_by(id: params[:hotelapp_id])
    @hotelapp = Hotelapp.find_by(params[:room_name])
  end

  def new
    @rent = Rent.new
    @hotelapp = Hotelapp.find(params[:hotelapp_id])
    @rent.hotelapp_id = @hotelapp.id #(hotelapp_params[:hotelapp]) 
  end

  #def confirm #予約確認
    #@rent = Rent.new(rent_params)
    #render :new unless @rent.invalid?
  #end

  def create
    #binding.pry
    @rent = Rent.new(rent_params)
    @hotelapp = Hotelapp.find(params[:rent][:hotelapp_id])
    @rent.hotelapp_id = @hotelapp.id
    #binding.pry
    if @rent.save
      redirect_to @rent, notice: "予約を完了しました。"
    else
      render :new
    end
    #if params[:back].present? #戻るボタン
      #render :new and return
    #end
  end

  private
    def rent_params
      params.require(:rent).permit(:id, :start_date, :end_date, :number, :hotelapp_id).merge(user_id: current_user.id)
    end
    
    def hotelapp_params
      params.require(:hotelapp).permit(:id, :name, :intro, :price, :address,).merge(user_id: current_user.id)
    end
  
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/confirm.html.slim
h1 予約内容の確認

h2 以下の詳細を確認してください

= form_with model: @rent, local:true do |f|
  .form-group
    = f.label :開始日
    = f.date_field :start_date, class: 'form-control', id: 'rent_start', as: 'hidden'
  .form-group
    = f.label :終了日
    = f.date_field :end_date, class: 'form-control', id: 'rent_end', as: 'hidden'
  .form-group
    = f.label :人数
    = f.number_field :number, class: 'form-control', id: 'rent_number', as: 'hidden'
  .form-group
    = f.label :hotelapp_id
    = f.hidden_field :hotelapp_id, id: 'rent_hotelapp_id', as: 'hidden'

    = f.submit '戻る', name: 'back', class: "btn btn-secondary"
    = f.submit '予約する', class: "btn btn-primary"
    

app/views/rents/index.html.slim
h1 予約ルーム一覧

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Hotelapp.human_attribute_name(:name)
      th= Hotelapp.human_attribute_name(:intro)
      th= Hotelapp.human_attribute_name(:address)
      th= Rent.human_attribute_name(:number)
      th= Rent.human_attribute_name(:total_price)
      th= Rent.human_attribute_name(:start_date)
      th= Rent.human_attribute_name(:end_date)
  tbody
    - @rents.each do |rent|
      tr
        td= link_to rent.hotelapp.name, rent_path(rent)
        td= rent.hotelapp.intro
        td= rent.hotelapp.address
        td= rent.number
        td= rent.hotelapp.price * rent.number * (rent.end_date - rent.start_date).to_i
        / 日数差、to_iで分子の形
        td= rent.start_date
        td= rent.end_date

app/views/rents/new.html.slim
h1 予約画面

- if @rent.errors.present?
  ul#error_explanation
    - @rent.errors.full_messages.each do |message|
      li= message

= form_with model: @rent, local: true do |f| #url: confirm_new_rent_path do |f|
  .form-group
    = f.label :開始日
    = f.date_field :start_date, class: 'form-control', id: 'rent_start'
  .form-group
    = f.label :終了日
    = f.date_field :end_date, class: 'form-control', id: 'rent_end'
  .form-group
    = f.label :人数
    = f.number_field :number, class: 'form-control', id: 'rent_number'
  .form-group
    = f.hidden_field :hotelapp_id, id: 'hotelapp_id'

  = f.submit '予約する', class: 'btn btn-primary'
  

app/views/rents/show.html.slim
h1 予約room詳細

.nav.justify-content-end
  =link_to '一覧', rents_path, class: 'nav-link'

table.table.table-hover
  tbody
    tr
      th= Hotelapp.human_attribute_name(:id)
      td= @rent.hotelapp_id
    tr
      th= Hotelapp.human_attribute_name(:name)
      td= @hotelapp.name
    tr
      th= Hotelapp.human_attribute_name(:intro)
      td= @hotelapp.intro
    tr
      th= Hotelapp.human_attribute_name(:price)
      td= @hotelapp.price
    tr
      th= Hotelapp.human_attribute_name(:address)
      td= @hotelapp.address