config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'hotelapps#top'
  get 'hotelapps/top', to: 'hotelapps#top', as: 'top_hotelapp'
  get 'users/show', to: 'users#show', as: 'show_user'
  #get 'rents/new/:id', to: 'rents#new', as: :rents_new #アクションでホテルのidを取得
  resources :users, only: [:show] 
  resources :hotelapps do
    resources :rents, only: [:new]
    collection do
      get 'search'
    end
  end
  resources :rents do
    #post :confirm, action: :confirm, on: :new
  end
  resources :users
  #resources :hotelapps だとhotelapps/topへのルーティングができなかった。なぜ？
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hotelapp.rb
class Hotelapp < ApplicationRecord
  belongs_to :user
  has_many :rents

  has_one_attached :room_image
  has_one_attached :avatar
end

app/controllers/hotelapps_controller.rb
class HotelappsController < ApplicationController
  before_action :search
  before_action :authenticate_user!, except: [:top, :search, :show]

  def search
    @search = Hotelapp.ransack(params[:q])
    @hotelapps = @search.result
    @q = Hotelapp.ransack(params[:q]) # params[:q]のqには検索フォームに入力した値が入る
    @hotelapps = @q.result(distinct: true) 
  end

  def top #ルーム一覧
    # 検索オブジェクト
    @search = Hotelapp.ransack(params[:q])
    # 検索結果
    @hotelapps = @search.result
    @hotelapps = @q.result(distinct: true) # distinct: trueは重複したデータを除外
    # @hotelapps = Hotelapp.all
  end

  def index #myルーム一覧
    @hotelapps = current_user.hotelapps
  end

  def show #myルーム詳細
    @hotelapps = Hotelapp.find(params[:id])
  end

  def new
    @hotelapp = Hotelapp.new
  end

  def create
    hotelapp = current_user.hotelapps.new(hotelapp_params)
    hotelapp.save!
    redirect_to hotelapps_url, notice: "ホテル「#{hotelapp.name}」を登録しました。"
  end

  def edit
    @hotelapp = current_user.hotelapps.find(params[:id])
  end

  def update
    hotelapp = current_user.hotelapps.find(params[:id])
    hotelapp.update!(hotelapp_params)
    redirect_to hotelapps_url, notice: "ホテル「#{hotelapp.name}」を更新しました。"
  end

  def destroy
    hotelapp = current_user.hotelapps.find(params[:id])
    hotelapp.destroy
    redirect_to hotelapps_url, notice: "ホテル「#{hotelapp.name}」を削除しました。"
  end

  private

  def hotelapp_params
    params.require(:hotelapp).permit(:id, :name, :intro, :price, :address, :room_image, :avatar).merge(user_id: current_user.id)
  end
end

app/helpers/hotelapps_helper.rb
module HotelappsHelper
end

app/views/hotelapps/edit.html.slim
h1 Hotelapps編集

.nav.justify-content-end
  =link_to '一覧', hotelapp_path, class: 'nav-link'

= form_with model: @hotelapp, local: true do |f|
  .form-group
    = f.label :room名
    = f.text_field :name, class: 'form-control', id: 'hotelapp_name'
  .form-group
    = f.label :紹介
    = f.text_field :intro, class: 'form-control', id: 'hotelapp_intro'
  .form-group
    = f.label :料金
    = f.text_field :price, class: 'form-control', id: 'hotelapp_price'
  .form-group
    = f.label :住所
    = f.text_field :address, class: 'form-control', id: 'hotelapp_address'
  .form-group
    = f.label :room画像
    = f.file_field :room_image, id: 'hotelapp_room_image' 

  = f.submit nil, class: 'btn btn-primary'

app/views/hotelapps/index.html.slim
h1 myルーム一覧

=link_to '新規ルーム登録', new_hotelapp_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Hotelapp.human_attribute_name(:name)
      th= Hotelapp.human_attribute_name(:intro)
      th= Hotelapp.human_attribute_name(:price)
      th= Hotelapp.human_attribute_name(:address)
  tbody
    - @hotelapps.each do |hotelapp|
      tr
        td= link_to hotelapp.name, hotelapp
        td= hotelapp.intro
        td= hotelapp.price
        td= hotelapp.address
        

app/views/hotelapps/new.html.slim
h1 ルームの新規登録
.nav.justify-content-end
  =link_to '一覧', hotelapps_path, class: 'nav-link'

= form_with model: @hotelapp, local: true do |f|
  .form-group
    = f.label :room名
    = f.text_field :name, class: 'form-control', id: 'hotelapp_name'
  .form-group
    = f.label :紹介
    = f.text_field :intro, class: 'form-control', id: 'hotelapp_intro'
  .form-group
    = f.label :料金
    = f.text_field :price, class: 'form-control', id: 'hotelapp_price'
  .form-group
    = f.label :住所
    = f.text_field :address, class: 'form-control', id: 'hotelapp_address'
  .form-group
    = f.label :room画像
    = f.file_field :room_image, id: 'hotelapp_room_image' 

  = f.submit nil, class: 'btn btn-primary'
  

app/views/hotelapps/search.html.slim
- if @hotelapps.present?
  .mb-3
  table.table.table-hover
    thead.thead-default
      tr
        th= Hotelapp.human_attribute_name(:name)
        th= Hotelapp.human_attribute_name(:intro)
        th= Hotelapp.human_attribute_name(:price)
        th= Hotelapp.human_attribute_name(:address)
    tbody
      - @hotelapps.each do |hotelapp|
        tr
          td= link_to hotelapp.name, hotelapp
          td= hotelapp.intro
          td= hotelapp.price
          td= hotelapp.address
  
- else
  p 検索結果はありません
  

app/views/hotelapps/show.html.slim
h1 myルーム詳細

.nav.justify-content-end
  =link_to '一覧', hotelapps_path, class: 'nav-link'

- if @hotelapps.room_image.attached?
  = image_tag @hotelapps.room_image.variant(resize:'200x200').processed 
end

table.table.table-hover
  tbody
    tr
      th= Hotelapp.human_attribute_name(:id)
      td= @hotelapps.id
    tr
      th= Hotelapp.human_attribute_name(:name)
      td= @hotelapps.name
    tr
      th= Hotelapp.human_attribute_name(:intro)
      td= @hotelapps.intro
    tr
      th= Hotelapp.human_attribute_name(:price)
      td= @hotelapps.price
    tr
      th= Hotelapp.human_attribute_name(:address)
      td= @hotelapps.address
  
=link_to '予約する', new_hotelapp_rent_path(@hotelapps), class: 'btn btn-primary mr-3'

- if user_signed_in?
  -if current_user.id == @hotelapps.user_id
    =link_to '編集', edit_hotelapp_path, class: 'btn btn-primary mr-3'
    =link_to '削除', @hotelapp, method: :delete, data: { confirm: "ホテル「#{@hotelapps.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'
//link_to, new_hotelapp_rent_path(@hotelapps)でidを通ったパスが受けられる

app/views/hotelapps/top.html.slim
h1 Hotelappトップ
h2 Potepan Shareでまだ体験したことのない旅をしよう

ul.list-unstyled.list-group.list-group-horizontal 
  li.list-group-item
    = search_form_for @q, class: 'mb-5', url: search_hotelapps_path do |f|
      .form-group
        = f.label :address_cont, 'エリア検索', class: 'col-form-label'
        .col-sm-10
          = f.search_field :address_cont
      .form-group
        = f.submit class: 'btn btn-outline-primary'

  li.list-group-item
    = search_form_for @q, class: 'mb-5', url: search_hotelapps_path do |f|
      .form-group
        = f.label :name_or_intro_cont, 'フリーワード検索', class: 'col-form-label'
        .col-sm-10
          = f.search_field :name_or_intro_cont
      .form-group
      = f.submit class: 'btn btn-outline-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Hotelapp.human_attribute_name(:name)
      th= Hotelapp.human_attribute_name(:intro)
      th= Hotelapp.human_attribute_name(:price)
      th= Hotelapp.human_attribute_name(:address)
  tbody
    - @hotelapps.each do |hotelapp|
      tr
        td= link_to hotelapp.name, hotelapp
        td= hotelapp.intro
        td= hotelapp.price
        td= hotelapp.address
        