config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'hotelapps#top'
  get 'hotelapps/top', to: 'hotelapps#top', as: 'top_hotelapp'
  get 'users/show', to: 'users#show', as: 'show_user'
  #get 'rents/new/:id', to: 'rents#new', as: :rents_new #アクションでホテルのidを取得
  resources :users, only: [:show] 
  resources :hotelapps do
    resources :rents, only: [:new]
    collection do
      get 'search'
    end
  end
  resources :rents do
    #post :confirm, action: :confirm, on: :new
  end
  resources :users
  #resources :hotelapps だとhotelapps/topへのルーティングができなかった。なぜ？
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.slim
- if user_signed_in?

    .position-absolute.top-0.start-50.translate-middle-x
      h4= current_user.name
    - if current_user.avatar.attached?
          = image_tag current_user.avatar.variant(resize:'100x100').processed 
    .position-absolute.top-0.end-0
      ul.list-style:none
        li= link_to '部屋を探す', top_hotelapp_path
        li= link_to 'myルーム一覧', hotelapps_path
        li= link_to '予約ルーム一覧', rents_path
        li= link_to '設定', show_user_path
        li= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header-nav"
- else
  .position-absolute.top-0.end-0
    ul
      li= link_to "ログイン", new_user_session_path, class: "header-nav"
      li= link_to "新規登録", new_user_registration_path, class: "header-nav"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Hotel
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light
      .navbar-brand Ruby on Rails 宿泊予約サイト
      = render 'layouts/header'
    .container
      - if flash.notice.present?
        .alert.alert-success= flash.notice
    = yield